#!/usr/bin/env bash
#A Bash script that displays To infinity and beyond indefinitely with a 2 sleep in between each iteration and I am invincible!! when receiving a SIGTERM signal.
trap "echo 'I am invincible!!!'" 15
i=0
while [ $i -lt 1 ]
do
  echo "To infinity and beyond"
  sleep 2
done
