#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 100, displays FizzBuzz when the number is a multiple of 3 and 5, Fizz when the number is a multiple of 3, Buzz when the number is a multiple of 5, otherwise display the number in a list format
for (( i=1; i<101; i++ ))
do
  if (( i % 15  == 0))
  then
    echo "FizzBuzz"
  elif (( i % 3 == 0 ))
  then
    echo "Fizz"
  elif (( i % 5 == 0 ))
  then
    echo "Buzz"
  else 
    echo "$i"
  fi
done
