#!/usr/bin/env bash
#A bash script that displays the content of the file /etc/passwd
FILE="/etc/passwd"
while read -r file
do
    username=$(echo "$file" | cut -d ':' -f1)
    userid=$(echo "$file" | cut -d ':' -f3)
    homedir=$(echo "$file" | cut -d ':' -f6)
    echo "$username:$userid:$homedir"
done < $FILE
