#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20 and displays 4 and then bad luch from China, 9 an then bas luck from Japan and 17 bad luck from Italy using while and case
i=1
while [ $i -lt 21 ]
do
  echo "$i"
  ((i++))
  case $i in
    "5")
      echo "bad luck from China"
      ;;
    "10")
      echo "bad luck from Japan"
      ;;
    "18")
      echo "bad luck from Italy"
      ;;
  esac
done              
