#!/usr/bin/env bash
#A Bash script that displays Best School 10 times but in the 4th iteration display bad luck and
#for the 8th iteration display good luck, using while, for, elif and else
i=1
while [ $i -lt 21 ]
do
  echo "$i"
  ((i++))
  case $i in
    "5")
      echo "bad luck from China"
      ;;
    "10")
      echo "bad luck from Japan"
      ;;
    "18")
      echo "bad luck from Italy"
      ;;
  esac
done              
