#!/usr/bin/env bash
#A Bash script that displays the time for 12 hours and 59 minutes using while
minutes=0
hours=0
while [ $hours -le 12 ]
do
  echo "Hour = $hours"
  while [ $minutes -le 60 ]
  do
    echo "$minutes"
    ((minutes++))
  done
  ((hours++))
done
