#!/usr/bin/env bash
#A Bash script that displays the content of the current directory in list
#format where only the part of the name after dash is displayed
for i in *
do
  echo "$i" | cut -d '-' -f2
done
