#!/usr/bin/env bash
#A Bash script that gives information about the school file
FILE=school
if test -e "$FILE"
then
	echo "$FILE file exist"
  if [[ ! -s $FILE ]]
  then
    echo "$FILE file is empty"
  else
    echo "$FILE file is not empty"
  fi
	if test -f "$FILE"
  then
    echo "$FILE school is a regular file"
  fi
else
  echo "$FILE file does not exist"
fi
